### ISSUE TITLE
Project added to vcpkg

### ISSUE THREAD

**Issue by globberwops** [eclipse-ecal/tcp_pubsub#19]
Dear all,

I have [added the project to vcpkg](https://github.com/microsoft/vcpkg/pull/28649) in case you want to add instructions to the README.

Cheers,
Martin

**Comment by FlorianReimold** [comment]
Thank you very much! If I read the PR discussion there correctly, you had to patch tcp_pubsub? What did you have to change! If possible, I would like to improve the upstream repo here!

**Comment by globberwops** [comment]
@FlorianReimold You're welcome!

[fix-package-config-file.patch](https://github.com/microsoft/vcpkg/pull/28649/files#diff-beb3f9cb8704c08ae29a73b3a835bd1622305c5ec5650ab8c3cf0ed75dab7400) uses [`find_dependency`](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html) instead of `find_package` to find `Threads` bc. it's recommended to be used in package config files.
The patch also makes sure that the dependency is found _before_ including `tcp_pubsubTargets.cmake`.
The most important change is to remove the absolute path from the `include` statement to ensure that the package config is relocatable.

[use-ports-for-asio-and-recycle.patch](https://github.com/microsoft/vcpkg/pull/28649/files#diff-0de0124b75359d9edb3df9d3ac57465a1dfdf3b8498729d7d7ba0c686e72520a) is specific to vcpkg and makes sure that the `asio` and `recycle` ports can be found.

I have also opened a [PR](https://github.com/steinwurf/recycle/pull/36) to add a CMake package config to `recycle`, but it hasn't been merged, yet.

**Comment by FlorianReimold** [comment]
@globberwops:

I modified the package config file according to your recommendations (PR is #20). It would be nice if you could quickly approve that this is exactly what you needed.

I however don't understand exactly, why the generated package config file wasn't relocatable, before. It contained the following code:

```cmake
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

[...]

INCLUDE("${PACKAGE_PREFIX_DIR}/lib/cmake/tcp_pubsub/tcp_pubsubTargets.cmake")
```

Shouldn't this evaluate to `${CMAKE_CURRENT_LIST_DIR}/../../../lib/cmake/tcp_pubsub/tcp_pubsubTargets.cmake`, which in shorter form is `${CMAKE_CURRENT_LIST_DIR}/tcp_pubsubTargets.cmake`?

**Comment by globberwops** [comment]
@FlorianReimold 

https://github.com/eclipse-ecal/tcp_pubsub/blob/d83c7c3a06fa9d39f115a77f246083b118d0562b/tcp_pubsub/cmake/tcp_pubsubConfig.cmake.in#L3

`PACKAGE_TCP_PUBSUB_INSTALL_CMAKE_DIR` resolves to an absolute path when the package config file is configured.

**Comment by FlorianReimold** [comment]
I merged the changes here and in my other libraries [fineFTP Server](https://github.com/eclipse-ecal/fineftp-server) and [Udpcap](https://github.com/eclipse-ecal/udpcap). I always try to keep those in sync to each other and use the best practice I currently know of.

I still don't understand, why `PACKAGE_TCP_PUBSUB_INSTALL_CMAKE_DIR` evaluates to an absolute path for you, as - for me - it evaluates to `${PACKAGE_PREFIX_DIR}/lib/cmake/tcp_pubsub/` and the PACKAGE_PREFIX_DIR to `${CMAKE_CURRENT_LIST_DIR}/../../../`, which is still a relative path.
But also it doesn't matter, if it works like this! Thanks for contributing! 👍🏻
